### ISSUE TITLE
Check for the module when running the module does not appear to validate anything

### ISSUE THREAD

**Issue by dcuomo** [microsoft/Convert-LBFO2SET#10]
If we're already running Convert-LBFO2Set, then why check that the module exists?

![image](https://user-images.githubusercontent.com/12801954/73313796-0d9c1000-41e1-11ea-8e1c-68f2ce68b5fe.png)

**Comment by JamesKehr** [comment]
Because the script doesn't have to come from the module. You can grab it directly from GitHub, or copy it between systems. This is a fail safe.

I always assume there will be someone, somewhere, who will run a script in a way I don't intend it to work, and then plan accordingly.
