### ISSUE TITLE
Made a mess of the hyper-v server I ran it on... UPDATE the video in the WIKI  and install instructions.

### ISSUE THREAD

**Issue by mydogsbc** [microsoft/Convert-LBFO2SET#14]
Challenge to get it to run first... (Install problem until I used the TLS1.2  command, Pester old version issue). Finally googled and solved those issues. Ran it as instructed ...Convert-LBFO2SET -lbfoteam TeamName -Setteam NewSwitchname. Pester tests al passed. RESULTS -- Old switch  changed from External to Internal with no host nics associated with it but all vnics still attached. New SETSWITCH created as external, associated the physical nics with the new switch but set it to dynamic (old one was set to hyper-v port) and no Vnics attached to it..... RESULT now I need to manually delete and recreate everything.

**Comment by dcuomo** [comment]
It's a bit difficult to decipher what happened without any screenshots or error messages. Is this a question for support or just letting us know that there was a problem in your environment?

I'll update the wiki installation to include a note that you might see an error on installation. A quick test shows that the error message is helpful though, with the -SkipPublisherCheck parameter recommended in the error message. Please let us know if you have any additional suggestions. Closing but please let us know if you have any follow-up questions.

![image](https://user-images.githubusercontent.com/12801954/133345350-31e0cd07-913c-4390-aed8-af1b9ee85f58.png)
