### ISSUE TITLE
This version of Windows is not yet certified for Convert-LBFO2SET

### ISSUE THREAD

**Issue by Sumnus00** [microsoft/Convert-LBFO2SET#17]
OS 名称:          Microsoft Windows Server 2022 Datacenter
OS 版本:          10.0.20348 暂缺 Build 20348

**Comment by enkelprifti98** [comment]
Getting the same issue with Windows Server 2022 Standard. It looks like the check happens here:

https://github.com/microsoft/Convert-LBFO2SET/blob/master/Convert-LBFO2SET.psm1#L104-L133
