### ISSUE TITLE
Script does not work with Pester v5

### ISSUE THREAD

**Issue by Brachus12** [microsoft/Convert-LBFO2SET#19]
With Pester 5.3.3 installed, the script will throw these errors about syntax incompatibilities:

Running tests.
_[-] OSValidation.HostOS.HYPER05: Must be Windows Server 2016, or Server 2019 365ms (271ms|93ms)
 RuntimeException: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
 RuntimeException: Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v4
 ParameterBindingException: Cannot retrieve the dynamic parameters for the cmdlet. Legacy Should syntax (without dashes) is not supported in Pester 5. Please refer to migration guide at: https://pester.dev/docs/migrations/v3-to-v
4
 at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Convert-LBFO2SET\2022.8.29.35\tests\unit\unit.tests.ps1:10_

**Comment by NOTNlCE** [comment]
Seeing this as well. Any workaround?

**Comment by JamesKehr** [comment]
I released an updated version today with Pester 5 compliance for unit.tests.ps1. Please try that and let me know if that resolves the issue in your environment.

https://www.powershellgallery.com/packages/Convert-LBFO2SET/2022.12.1.36

**Comment by JamesKehr** [comment]
You're welcome. Closing this issue.
